### ISSUE TITLE
TypeError with werkzeug.debug.get_pin_and_cookie_name

### ISSUE THREAD

**Issue by jscholes** [pallets/werkzeug#899]
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32/Windows 7

When running the most basic of Flask apps with app.debug set to True, I see the following traceback and the app exits:

    Traceback (most recent call last):
      File "test.py", line 11, in <module>
        app.run(debug=True)
      File "C:\Users\jscholes\dev\fileserve\env\lib\site-packages\flask\app.py", line 772, in run
        run_simple(host, port, self, **options)
      File "C:\Users\jscholes\dev\fileserve\env\lib\site-packages\werkzeug-0.12.dev0-py3.4.egg\werkzeug\serving.py", line 634, in run_simple
        application = DebuggedApplication(application, use_evalex)
      File "C:\Users\jscholes\dev\fileserve\env\lib\site-packages\werkzeug-0.12.dev0-py3.4.egg\werkzeug\debug\__init__.py", line 249, in __init__
        if self.pin is None:
      File "C:\Users\jscholes\dev\fileserve\env\lib\site-packages\werkzeug-0.12.dev0-py3.4.egg\werkzeug\debug\__init__.py", line 259, in _get_pin
        self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
      File "C:\Users\jscholes\dev\fileserve\env\lib\site-packages\werkzeug-0.12.dev0-py3.4.egg\werkzeug\debug\__init__.py", line 169, in get_pin_and_cookie_name
        h.update('cookiesalt')
    TypeError: Unicode-objects must be encoded before hashing

    >>> import werkzeug
    >>> werkzeug.__version__
    '0.12-dev'
    >>> import flask
    >>> flask.__version__
    '0.10.1'

The simple app:

    from flask import Flask
    app = Flask(__name__)
    
    
    @app.route('/')
    def index():
        return 'Hello world'
    
    
    if __name__ == '__main__':
        app.run(debug=True)

I can get around this issue by setting the WERKZEUG_DEBUG_PIN environment variable to "off", but I don't imagine this is very good practice for most projects.

**Comment by untitaker** [comment]
This is fixed in the latest Werkzeug release, which is 0.11.7.

**Comment by jscholes** [comment]
You asked me to submit a full traceback in a new issue.  I have now done
so.  You can clearly see from my issue description that I'm running
0.12-dev, which I cloned from GitHub not six hours ago.  And the issue
still occurs.

**Comment by untitaker** [comment]
This line from your traceback:

    h.update('cookiesalt')

is neither in the current master nor the latest release. The line now looks like this:

    h.update(b'cookiesalt')

Please do `pip uninstall werkzeug` and ensure you've actually installed the latest version.

**Comment by untitaker** [comment]
More complete answer: You can't infer from the version `0.12-dev`whether you have the fix, as we do releases from multiple branches (so we can create 0.11 releases even if 0.12 is out). Pip can't figure this out, and doesn't bother updating. Consequently you end up with the old version even when running `pip install` again.

**Comment by jscholes** [comment]
Thanks a lot.  It was completely my mistake.  Pip hadn't fully uninstalled 0.11.  After updating master and installing via setup.py all is okay.

**Comment by untitaker** [comment]
Glad to hear that it works.
